server:
  port: 8000

spring:
  datasource:
    # url: jdbc:postgresql://localhost:5433/sptest
    url: jdbc:postgresql://ccproject.ct0nmr7fxogl.ap-south-1.rds.amazonaws.com/
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    # generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        id:
          new_generator_mappings: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
      database: postgresql

# spring.jpa.properties.hibernate.id.new_generator_mappings=false
#spring:
#  main:
#    web-application-type: none