server:
  port: 8000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/sptest
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
      database: postgresql

#spring:
#  main:
#    web-application-type: none